logo_title: Notes

style: black

favicon: /favicon.ico

menu:
  # Projects: /projects
  # 域名: /domain
  # 友联: /links
  # About: /about
  Archives: /archives
  Github: https://github.com/theanhnguyenhoang

# 做了域名限制，请改成自己的 KEY
valine:
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false
